#logging.level.org.apache.coyote.http11=debug
spring.messages.basename=messages,errors 
#basename\uC744 errors\uAE4C\uC9C0 \uCD94\uAC00\uD574\uC57C \uAE30\uBCF8\uAC12\uC73C\uB85C \uC0AC\uC6A9\uD55C\uB2E4.
spring.messages.fallback-to-system-locale=false